"use client";
import {useState} from 'react';
import {ArrowUpRight,ArrowLeft,Activity,Database,GitBranch,ShieldCheck} from 'lucide-react';
import data from './data.json';
const money=(v:number|null)=>v===null?'—':v.toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const pct=(v:number|null)=>v===null?'—':`${v>0?'+':''}${v.toFixed(2)}%`;
export default function Dashboard(){
 const [id,setId]=useState('scalper'),[point,setPoint]=useState<number|null>(null),[filter,setFilter]=useState('全部');
 const a=data.accounts.find(x=>x.id===id)!;
 const pts=a.points,selected=point===null?pts.length-1:Math.min(point,pts.length-1);
 const low=Math.min(...pts.map(p=>p.value)),high=Math.max(...pts.map(p=>p.value)),spread=Math.max(high-low,1);
 const coord=(i:number)=>({x:70+i/Math.max(pts.length-1,1)*810,y:35+(high-pts[i].value)/spread*200});
 const line=pts.map((_,i)=>`${coord(i).x},${coord(i).y}`).join(' ');
 const trades=[...a.trades].reverse().filter(t=>filter==='全部'||(filter==='盈利'?(t.pnl??t.pnlPct??0)>0:(t.pnl??t.pnlPct??0)<=0));
 const choose=(value:string)=>{setId(value);setPoint(null);setFilter('全部')};
 return <div className="quant-page"><header className="quant-nav"><a href="../"><ArrowLeft size={16}/> YANG / 作品集</a><a href="../projects/ml/">工程案例 <ArrowUpRight size={16}/></a></header><main className="quant-shell">
 <section className="quant-hero"><div><p className="q-eyebrow"><span/> AI QUANT / PAPER TRADING</p><h1>让策略接受<br/><em>真实记录的检验。</em></h1><p className="q-intro">模型筛选、虚拟执行、交易复盘。<br/>把 AI 量化系统的运行过程，变成可以检查的工程证据。</p></div><div className="q-orbit" aria-hidden="true"><div/><div/><div/><span>MODEL<br/><b>→ EXECUTION</b><br/>→ REVIEW</span></div></section>
 <div className="q-snapshot"><span><Activity size={15}/> 离线数据快照 · 非实时行情</span><span>导入 {data.importedAt.slice(0,10)} · 最新交易记录 2026-09-18 · CNY</span></div>
 <section className="q-overview" aria-label="数据覆盖"><div><strong>{data.accounts.length}</strong><span>账户 / 会话记录 · 含重叠</span></div><div><strong>{data.accounts.filter(a=>a.points.length>1).length}</strong><span>可查看的历史曲线</span></div><div><strong>{data.accounts.filter(a=>a.kind==='待补净值').length}</strong><span>待补净值的策略账户</span></div><div><strong>{data.sources.length}</strong><span>已核对源文件</span></div></section>
 <section className="q-terminal" aria-labelledby="terminal-title"><div className="q-terminal-top"><div><p className="q-eyebrow">01 / STRATEGY OBSERVATORY</p><h2 id="terminal-title">虚拟盘观察台</h2></div><label>切换策略记录<select aria-label="切换策略记录" value={id} onChange={e=>choose(e.target.value)}>{data.accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label></div>
 <div className="q-account-heading"><h3>{a.name}</h3><span>{a.kind} · {a.date}</span></div>
 <div className="q-metrics"><div><small>{id==='scalper'?'归一基准 + 已平仓净盈亏':'记录权益'}</small><strong>¥ {money(a.equity)}</strong></div><div><small>{id==='scalper'?'已平仓净盈亏 / 归一基准':'相对初始资金'}</small><strong className={(a.returnPct??0)<0?'q-loss':'q-gain'}>{pct(a.returnPct)}</strong></div><div><small>{id==='scalper'?'重建曲线最大回撤':'观测点最大回撤'}</small><strong>{a.drawdown===null?'—':a.drawdown.toFixed(2)+'%'}</strong></div><div><small>{id==='scalper'?'归一计算基准':'源记录初始资金'}</small><strong>¥ {money(a.initial)}</strong></div></div>
 {pts.length>1?<div className="q-chart"><div className="q-chart-caption"><span>{a.basis}</span><strong aria-live="polite">{pts[selected]?.date} · ¥ {money(pts[selected]?.value??null)}</strong></div><svg viewBox="0 0 920 295" role="img" aria-label={`${a.name}，${pts.length} 个观测日，最新值 ${money(a.equity)} 元`}><defs><linearGradient id="q-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#f6cc62" stopOpacity=".24"/><stop offset="100%" stopColor="#f6cc62" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3].map(i=><g key={i}><line x1="70" y1={35+i*200/3} x2="880" y2={35+i*200/3} stroke="#ffffff16"/><text x="0" y={39+i*200/3} fill="#9faaa8" fontSize="12">{Math.round(high-i*spread/3).toLocaleString()}</text></g>)}<polygon points={`70,240 ${line} 880,240`} fill="url(#q-fill)"/><polyline points={line} fill="none" stroke="#f6cc62" strokeWidth="3" strokeLinejoin="round"/>{pts.map((p,i)=><circle key={p.date} cx={coord(i).x} cy={coord(i).y} r={i===selected?6:3} fill={i===selected?'#fff4cc':'#f6cc62'} onMouseEnter={()=>setPoint(i)}><title>{`${p.date}: ${money(p.value)}`}</title></circle>)}<line x1={coord(selected).x} x2={coord(selected).x} y1="25" y2="240" stroke="#f6cc6270" strokeDasharray="4 5"/><text x="70" y="278" fill="#9faaa8" fontSize="13">{pts[0].date}</text><text x="880" y="278" textAnchor="end" fill="#9faaa8" fontSize="13">{pts[pts.length-1].date}</text></svg><label className="q-slider">滑动 / 方向键查看日期<input aria-label="查看曲线日期" type="range" min="0" max={pts.length-1} value={selected} onChange={e=>setPoint(Number(e.target.value))}/></label></div>:<div className="q-no-history"><Database size={30}/><h4>{a.equity===null?'持仓已记录，净值待补全。':'已载入权益快照。'}</h4><p>{a.equity===null?'补充估值价格与历史后，才能展示收益曲线。':'当前记录不足以形成历史曲线，暂不计算回撤。'}</p></div>}
 <p className="q-method"><ShieldCheck size={18}/>{a.note}</p>
 {a.trades.length>0&&<section className="q-trades"><div className="q-trades-heading"><h3>交易复盘 <span>{a.trades.length} 条{id==='scalper'?'合并持仓':'卖出记录'}</span></h3><div className="q-filter">{['全部','盈利','亏损 / 持平'].map(f=><button key={f} aria-pressed={f===filter} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><p>{a.tradeNote} 显示 {trades.length} 条。</p><div className="q-table-wrap" tabIndex={0} aria-label="交易明细，可横向滚动"><table><thead><tr>{['退出日期','标的','版本','股数','盈亏 / CNY','退出原因'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{trades.map((t,i)=><tr key={i}><td>{t.date}</td><td>{t.symbol}</td><td>{t.version}</td><td>{t.shares.toLocaleString()}</td><td className={(t.pnl??t.pnlPct??0)<0?'q-loss':'q-gain'}>{money(t.pnl)}{t.pnl===null&&t.pnlPct!==null&&<small style={{display:"block"}}>比例 {pct(t.pnlPct*100)}</small>}</td><td>{t.reason}</td></tr>)}</tbody></table></div></section>}{a.trades.length===0&&<section className="q-trades"><h3>交易明细</h3><p>暂无可用成交明细。{a.tradeNote}</p></section>}
 </section>
 <section className="q-inventory"><p className="q-eyebrow">02 / FULL INVENTORY</p><h2>每一份记录，都有位置。</h2><p>同一策略的会话、子账户与历史存在重叠，因此不计算跨账户“总收益”。点击任意记录查看。</p><div className="q-record-grid">{data.accounts.map(r=><button key={r.id} aria-pressed={id===r.id} onClick={()=>{choose(r.id);document.getElementById('terminal-title')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}}><span>{r.kind}</span><strong>{r.name}</strong><div><span>{r.date}</span><b className={(r.returnPct??0)<0?'q-loss':''}>{pct(r.returnPct)}</b></div></button>)}</div></section>
 <section className="q-engineering"><div><p className="q-eyebrow">03 / ENGINEERING VALUE</p><h2>从模型到执行，<br/>把验证留在系统里。</h2><a href="../projects/ml/">查看完整工程案例 <ArrowUpRight size={17}/></a></div><div className="q-capabilities">{[[GitBranch,'策略与模型','并行保留动量策略、TradingAgents 与 V17 ML 筛选的运行记录，比较各自表现。'],[ShieldCheck,'成本与资金口径','处理分批成交、双边佣金和组合资金迁移，让指标能被复核。'],[Database,'可追溯的数据导入','只读抽取白名单字段，保留源文件指纹，展示数据缺口，支持重新导入。']].map(([Icon,title,desc])=>{const I=Icon as typeof Database;return <article key={String(title)}><I size={21}/><h3>{String(title)}</h3><p>{String(desc)}</p></article>})}</div></section>
 <details className="q-sources"><summary>数据口径与来源 · {data.sources.length} 个源文件</summary><p>展示虚拟交易记录，不代表实盘收益。曲线未年化；快照回撤仅覆盖观测点；缺失数据不按 0 补齐。Scalper 的重建曲线包含不同版本的历史成交，用于复盘，不代表单一版本策略的收益验证。</p><h3>排除与覆盖说明</h3><ul>{data.excluded.map(s=><li key={s}>{s}</li>)}</ul><h3>源文件与 SHA-256 指纹</h3>{data.sources.map(s=><p key={s.file}><strong>{s.file}</strong><code>{s.sha256}</code></p>)}</details>
 <footer className="q-footer"><span>YANG / AI QUANT ENGINEERING</span><a href="../">返回作品集 ↑</a></footer></main></div>
}
