import {readFileSync} from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const html=readFileSync('public/hot-bounce/index.html','utf8');new vm.Script([...html.matchAll(/<script>([\s\S]*?)<\/script>/g)][0][1]);const ctx=vm.createContext({});vm.runInContext(html.split('// PHYSICS_START')[1].split('// PHYSICS_END')[0]+';globalThis.api={newRun,tick,contact,orbitPoint,FLOOR,registerHit,TIME_SCALE,MAX_PACE,nextLayer,refillCandidates,hitsOuterHemisphere};',ctx);const {newRun,tick,contact,orbitPoint,FLOOR}=ctx.api;
const fresh=newRun();tick(fresh,[],0);assert.equal(fresh.dead,false);assert.ok(fresh.radius>FLOOR);let n=0;while(!fresh.dead&&n++<300)tick(fresh,[],0);assert.equal(fresh.dead,true);assert.equal(fresh.radius,FLOOR);assert.ok(n>=90);
const upper=newRun();tick(upper,[{x:upper.x,y:upper.y-.6,z:upper.z,r:.5,red:true}],0);assert.equal(upper.dead,true);
const lower=newRun(),gold={x:lower.x,y:lower.y+.6,z:lower.z,r:.5,red:true};tick(lower,[gold],0);assert.equal(lower.dead,false);assert.equal(lower.score,100);assert.equal(gold.taken,true);tick(lower,[gold],0);assert.equal(lower.score,100);
assert.ok(contact({x:0,y:0,z:0},{x:0,y:-2,z:0},{x:0,y:2,z:0},.95).y<0);
const climb=newRun();const balls=Array.from({length:30},(_,i)=>({...orbitPoint(Math.PI/2,8.4+i*2.8),r:.38,red:false,taken:false}));for(let i=0;i<1400&&!climb.dead;i++)tick(climb,balls,0);assert.ok(climb.peak>40,'Consecutive boosts must climb beyond old radius ceiling');assert.ok(climb.score>=1000);
assert.ok(html.includes('altitude<game.peak-18'));assert.ok(html.includes('cameraTarget'));console.log('PASS: safe launch, landing death, upper-red death, lower-red consumption/boost, single scoring, first-contact hemisphere, sustained climb beyond 40 units, cleanup and tracking');
const noBall=newRun();let duration=0;while(!noBall.dead&&duration++<400)tick(noBall,[],0);assert.ok(duration>=125,'Slow launch should give at least 2 seconds to react');
const high=newRun();high.radius=80;Object.assign(high,orbitPoint(high.angle,80));high.target=0;let previousAngle=high.angle;for(let i=0;i<80;i++){tick(high,[],0);assert.ok(Math.abs(high.angle-previousAngle)*high.radius*60<5,'Tangential speed must stay bounded at high altitude');previousAngle=high.angle;}
assert.ok(html.includes('52+7*Math.min(1,filteredSpeed/9)'));assert.ok(html.includes('previousPosition.x+(game.x-previousPosition.x)*blend'));console.log('PASS: slower reaction window, altitude-independent turn speed, render interpolation, bounded smooth FOV');
const routeRun=newRun();const routeBalls=Array.from({length:40},(_,i)=>{const radius=8.4+i*2.8;return {...orbitPoint(Math.PI/2+.4*Math.log(radius/8.4),radius),angle:Math.PI/2+.4*Math.log(radius/8.4),r:.38,red:false,taken:false}});for(let i=0;i<5000&&!routeRun.dead;i++){const next=routeBalls.find(o=>!o.taken);if(next)routeRun.target=next.angle;tick(routeRun,routeBalls,0);if(routeRun.peak>80)break}assert.ok(routeRun.peak>80,'Slow steering must still reach generated white path at altitude');console.log('PASS: generated white path remains reachable past 80 units with slower controls');

const {registerHit,TIME_SCALE,MAX_PACE}=ctx.api;assert.equal(TIME_SCALE,.35);const streak=newRun();registerHit(streak);const firstGain=streak.paceTarget-TIME_SCALE;assert.ok(firstGain>0&&firstGain>.013&&firstGain<.015);const beforeSecond=streak.paceTarget;registerHit(streak);assert.ok(streak.paceTarget-beforeSecond>firstGain);assert.equal(streak.combo,2);assert.equal(streak.pace,TIME_SCALE,'Speed must interpolate, not jump on contact');tick(streak,[],0);assert.ok(streak.pace>TIME_SCALE&&streak.pace<streak.paceTarget);for(let i=0;i<100;i++)registerHit(streak);assert.equal(streak.paceTarget,MAX_PACE);const cap=streak.paceTarget;streak.clock+=181;registerHit(streak);assert.equal(streak.combo,1);assert.equal(streak.paceTarget,cap);assert.equal(newRun().pace,TIME_SCALE);assert.equal(newRun().combo,0);console.log('PASS: updated faster baseline, gentle gains, increasing combo gains, smoothed acceleration, speed cap, combo reset and restart');


const {nextLayer}=ctx.api;
for(let seed=1;seed<=20;seed++){let s=seed;const random=()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296};const layout={radius:8.2,focusAngle:Math.PI/2},routes=Array.from({length:8},()=>[]);for(let n=0;n<24;n++){const points=nextLayer(layout,random);assert.ok(points.length<=16);for(let k=0;k<8;k++){const p=points.find(o=>o.route===k);assert.ok(p&&!p.red);routes[k].push({...p,r:.38,taken:false})}}
for(let k=0;k<8;k++){const run=newRun();run.angle=run.target=routes[k][0].angle;Object.assign(run,orbitPoint(run.angle,FLOOR));for(let n=0;n<4000&&!run.dead&&run.peak<60;n++){const next=routes[k].find(o=>!o.taken);if(next)run.target=next.angle;tick(run,routes[k],0)}assert.ok(run.peak>60,'All eight routes reachable: '+seed+'/'+k)}}
const push=newRun();registerHit(push);assert.equal(push.vr,.48);assert.ok((.48*.48)/(.39*.39)>1.5);console.log('PASS: eight continuous routes across 20 seeds, bounded irregular density, stronger contact impulse and over 50% greater theoretical jump range');

const {refillCandidates}=ctx.api;const refillRun=newRun();refillRun.radius=22;refillRun.peak=22;Object.assign(refillRun,orbitPoint(refillRun.angle,22));let stock=[];for(let cycle=0;cycle<100;cycle++){refillRun.target=cycle*.19;const additions=refillCandidates(refillRun,stock,()=>.42);for(const o of additions){assert.ok(Math.hypot(o.x-refillRun.x,o.y-refillRun.y,o.z-refillRun.z)>=(o.red?5:2.5))}stock.push(...additions);stock=stock.slice(3);assert.ok(additions.length<=5)}assert.ok(stock.length<100);const empty=refillCandidates(refillRun,[],()=>.42);assert.ok(empty.length>0,'Must regenerate at unchanged peak');refillRun.target+=Math.PI;assert.ok(refillCandidates(refillRun,[],()=>.55).length>0,'Turning must replenish another direction');assert.ok(html.includes('game.clock+45'));assert.ok(html.includes('items.length>=180'));console.log('PASS: continuous refill without new altitude record, changed-direction refill, safe red and white spawning distances, bounded refill batch and scene cap');

let hazardSeed=44;const hazardRandom=()=>{hazardSeed=(Math.imul(hazardSeed,1664525)+1013904223)>>>0;return hazardSeed/4294967296};let hazards=0;const hazardLayout={radius:12,focusAngle:0};for(let i=0;i<100;i++)hazards+=nextLayer(hazardLayout,hazardRandom).filter(o=>o.red).length;assert.ok(hazards>300,'Increased red density across randomized layers');let hitsToCap=0;const acceleration=newRun();while(acceleration.paceTarget<MAX_PACE&&hitsToCap<30){registerHit(acceleration);hitsToCap++}assert.ok(hitsToCap<=8);console.log('PASS: '+hazards+' red balls across 100 generated layers; speed reaches cap after '+hitsToCap+' consecutive hits');

const {hitsOuterHemisphere}=ctx.api;
for(const axis of [{x:1,y:0,z:0},{x:-1,y:0,z:0},{x:0,y:1,z:0},{x:0,y:-1,z:0},{x:0,y:0,z:1},{x:0,y:0,z:-1},{x:.6,y:.8,z:0}]){const o={x:axis.x*12,y:axis.y*12,z:axis.z*12};const inward={x:o.x-axis.x,y:o.y-axis.y,z:o.z-axis.z},outward={x:o.x+axis.x,y:o.y+axis.y,z:o.z+axis.z};assert.equal(hitsOuterHemisphere(o,inward),false);assert.equal(hitsOuterHemisphere(o,outward),true);const swept=contact(o,{x:o.x-axis.x*2,y:o.y-axis.y*2,z:o.z-axis.z*2},outward,.95);assert.equal(hitsOuterHemisphere(o,swept),false)}
for(let i=0;i<8;i++){const angle=i*Math.PI/4;const inner=newRun();inner.angle=inner.target=angle;inner.radius=12;Object.assign(inner,orbitPoint(angle,12));const gold={...orbitPoint(angle,12.6),r:.5,red:true};tick(inner,[gold],0);assert.equal(inner.dead,false);assert.equal(gold.taken,true);const outer=newRun();outer.angle=outer.target=angle;outer.radius=12;Object.assign(outer,orbitPoint(angle,12));tick(outer,[{...orbitPoint(angle,11.4),r:.5,red:true}],0);assert.equal(outer.dead,true)}
assert.ok(html.includes('mesh.quaternion.setFromUnitVectors'));console.log('PASS: radial orientation and first-contact hemisphere on all axes; eight orbital positions reward inward contacts and reject outward contacts');
