"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, ArrowDown, ArrowRight, Code2, Mail, Menu, X, Check, Copy, Pause, Play, Layers, Workflow, ShieldCheck, Braces, Sparkles, ChevronRight } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import {useSiteMotion} from "./site-motion";
import TechField from "./tech-field";
import OrbitGame from "./orbit-game";
import { projects, categories, toolIds, type Project } from "./projects";

function Diagram({kind}:{kind:string}){
 if(kind==="yundai")return <div className="diagram finance-diagram"><div className="diagram-top"><span><i/> FINANCING INTELLIGENCE</span><span>ARCHITECTURE / 01</span></div><div className="profile-node"><span className="node-icon"><Layers size={22}/></span><div><small>INPUT</small><strong>经营画像</strong></div><span className="node-state">结构化</span></div><div className="connection"/><div className="engine-row"><div className="engine"><ShieldCheck size={20}/><small>DETERMINISTIC</small><strong>规则引擎</strong><span>产品准入 · 候选排序</span></div><div className="engine ai-engine"><Sparkles size={20}/><small>CONSTRAINED AI</small><strong>辅助分析</strong><span>场景选择 · 输出校验</span></div></div><div className="connection"/><div className="result-node"><Check size={18}/><span>可解释报告</span><span className="review-label">顾问复核</span></div><div className="diagram-foot"><span>RULES FIRST. AI WITHIN REACH.</span><span>流程示意</span></div></div>;
 if(kind==="geo")return <div className="diagram content-diagram"><div className="diagram-top"><span><i/> CONTENT WORKFLOW</span><span>ARCHITECTURE / 02</span></div><div className="paper-stack"><div className="paper-back"/><div className="paper-front"><span className="paper-kicker">SOURCE → STORY</span><div className="paper-heading">每一段内容，<br/>都有据可循。</div><div className="paper-line"/><div className="paper-line short"/><div className="paper-label"><ShieldCheck size={15}/> 事实一致性检查</div><div className="scan-line"/></div><div className="floating-tag"><Check size={14}/> 质量门禁</div></div><div className="pipeline-mini"><span>素材</span><ChevronRight size={15}/><span>生成</span><ChevronRight size={15}/><span>校验</span><ChevronRight size={15}/><span>发布</span></div><div className="diagram-foot"><span>GENERATE. CHECK. DELIVER.</span><span>流程示意</span></div></div>;
 if(kind==="accounting")return <div className="diagram accounting-diagram"><div className="diagram-top"><span><i/> DOCUMENT ENGINEERING</span><span>ARCHITECTURE / 03</span></div><div className="document-transform"><div className="document-sheet"><span>TRANSACTION REPORT</span><b>PDF</b><div/><div/><div/><p>EUR · JPY · USD</p></div><div className="transform-arrow"><ArrowRight size={28}/></div><div className="spreadsheet"><div className="sheet-head">科目 <span>金额</span></div>{["Income","Expenses","Transfers","Tax"].map((x,i)=><div key={x} className="sheet-row"><span>{x}</span><span className={"cell cell-"+i}/><Check size={12}/></div>)}<div className="sheet-bottom">映射 → 校验 → 人工复核</div></div></div><div className="locale-row">EN <span>DE</span> FR <span>ES</span> IT <span>JA</span> +5</div><div className="diagram-foot"><span>COMPLEX INPUT. STRUCTURED OUTPUT.</span><span>流程示意</span></div></div>;
 return <div className="diagram ml-diagram"><div className="diagram-top"><span><i/> AI QUANT ENGINEERING</span><span>PAPER / 04</span></div><div className="experiment-title"><small>INTERACTIVE OBSERVATORY</small><strong>模型。执行。复盘。</strong></div><div className="engine-row" style={{margin:'36px 0'}}><div className="engine"><strong>15</strong><span>账户 / 会话记录</span></div><div className="engine ai-engine"><strong>11</strong><span>核对源文件</span></div></div><div className="split-track"><span>STRATEGY</span><span>EXECUTE</span><span>REVIEW</span></div><div className="diagram-foot"><span>EXPLORE THE PAPER TRADING DATA</span><span>虚拟盘 · 含重叠记录</span></div></div>
}
export default function Home(){
 const [active,setActive]=useState<Project|null>(null),[filter,setFilter]=useState("全部"),[menu,setMenu]=useState(false),[paused,setPaused]=useState(false),[copied,setCopied]=useState(false);
 useSiteMotion(paused);
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{const els=document.querySelectorAll(".reveal, .motion-reveal");const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");observer.unobserve(e.target)}}),{threshold:.07});els.forEach(x=>observer.observe(x));return()=>{observer.disconnect();if(timer.current)clearTimeout(timer.current)}},[]);
 useEffect(()=>{const sync=()=>{const p=projects.find(x=>"#project-"+x.id===location.hash);setActive(p??null)};const frame=requestAnimationFrame(sync);window.addEventListener("hashchange",sync);return()=>{cancelAnimationFrame(frame);window.removeEventListener("hashchange",sync)}},[]);
 const open=(p:Project)=>{location.href="./projects/"+p.id+"/"};
 const close=()=>{setActive(null);history.replaceState(null,"",location.pathname+location.search)};
 const copy=async()=>{try{await navigator.clipboard.writeText("249562189@qq.com");setCopied(true);timer.current=setTimeout(()=>setCopied(false),2500)}catch{location.href="mailto:249562189@qq.com"}};
 const featured=projects.slice(0,4),filtered=projects.filter(p=>filter==="全部"||p.category===filter);
 return <div className={paused?"portfolio motion-stage motion-paused":"portfolio motion-stage"}>
  <a className="skip-link" href="#main">跳至主要内容</a>
  <header className="header"><div className="nav-wrap"><a className="brand" href="#main" aria-label="小杨作品集首页">Y<span>·</span><span className="brand-name">YANG<span>AI APPLICATION ENGINEER</span></span></a><nav className={menu?"nav-links open":"nav-links"} aria-label="主导航">{[["工具入口","#tools"],["精选案例","#work"],["项目库","#library"],["个人名片","./profile/"]].map(([t,h])=><a key={h} href={h} onClick={()=>setMenu(false)}>{t}</a>)}<a className="nav-contact" href="#contact" onClick={()=>setMenu(false)}>聊聊机会 <ArrowUpRight size={16}/></a></nav><button className="menu-toggle" aria-label={menu?"关闭导航":"打开导航"} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
  <main id="main" className="site-shell">
   <section className="hero"><TechField paused={paused}/><div className="hero-text"><div className="eyebrow"><i/> AI APPLICATIONS & ENGINEERING</div><h1>让 AI 的能力，<br/><em>成为业务的日常。</em></h1><p className="hero-copy">我是小杨。聚焦大模型应用、业务自动化与数据工程，<br/>把复杂的问题，做成清晰、可靠、可使用的产品。</p><div className="hero-actions"><a className="button" href="#work">探索精选案例 <ArrowUpRight size={19}/></a><a className="text-link" href="https://github.com/s1166921-png" target="_blank" rel="noreferrer"><Code2 size={17}/> GitHub <ArrowUpRight size={14}/></a></div><div className="hero-note"><span>LLM 工作流</span><span>业务系统</span><span>AI 量化工程</span></div></div><div className="hero-art"><OrbitGame paused={paused}/><button className="motion-toggle" onClick={()=>setPaused(!paused)} aria-label={paused?"播放页面动画":"暂停页面动画"} aria-pressed={paused}>{paused?<Play size={14}/>:<Pause size={14}/>}</button></div></section>
<section id="tools" className="section tools-section"><div className="section-heading motion-reveal"><div><p className="eyebrow">TOOL DIRECTORY / EXPLORE THE BUILD</p><h2>看见能力。<br/><span>也能走进产品。</span></h2></div><p>从业务场景到实现细节，<br/>每个工具都有自己的项目档案。</p></div><div className="tool-grid">{toolIds.map((id,i)=>{const p=projects.find(x=>x.id===id)!;return <article className={"tool-card motion-reveal motion-variant-"+i} data-motion-surface key={id}><div className="tool-card-top"><span>0{i+1} / {id.toUpperCase()}</span><span>{p.status}</span></div><div className="tool-circuit" aria-hidden="true"><i/><i/><i/><i/><b>{['CONNECT','MATCH','QUERY','GENERATE','AUTOMATE','QUANT'][i]}</b></div><h3><a href={"./projects/"+id+"/"}>{p.title}</a></h3><p>{p.summary}</p><div className="tool-card-actions"><a href={"./projects/"+id+"/"}>项目详情 <ArrowRight size={17}/></a>{p.id==="ml"?<a href="./quant/">虚拟盘演示<ArrowUpRight size={16}/></a>:p.links?.[0]?<a href={p.links[0].url} target="_blank" rel="noopener noreferrer">{p.links[0].kind}<ArrowUpRight size={16}/></a>:p.evidence[0]&&<a href={p.evidence[0][1]} target="_blank" rel="noopener noreferrer">查看源码<ArrowUpRight size={16}/></a>}</div></article>})}</div></section><section id="work" className="section work-section"><div className="section-heading reveal"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>不止于想法。<br/><span>更在于如何实现。</span></h2></div><p>四个切面，看见我如何连接<br/>模型能力、工程设计与真实业务。</p></div>
    {featured.map((p,i)=><article key={p.id} className={"feature-project reveal "+p.color+(i%2?" reversed":"")}><button className="project-visual" data-motion-surface aria-label={"查看"+p.title+"案例"} onClick={()=>open(p)}><Diagram kind={p.id}/><span className="visual-open"><ArrowUpRight size={20}/></span></button><div className="project-story"><div className="project-topline"><span className="project-number">{p.number} —</span><span>{p.category}</span><span className="status"><i/>{p.status}</span></div><p className="project-english">{p.en}</p><h3>{p.title}</h3><p className="project-tagline">{p.tagline}</p><p className="project-summary">{p.summary}</p><div className="project-stats"><div><strong>{p.metric}</strong><span>{p.metricLabel}</span></div><div><strong>{p.second}</strong><span>{p.secondLabel}</span></div></div><div className="tags">{p.stack.map(t=><span key={t}>{t}</span>)}</div><button className="case-link" onClick={()=>open(p)}>阅读项目案例 <ArrowUpRight size={18}/></button>{p.id==="ml"&&<a className="case-link" href="./quant/">体验虚拟盘观察台 <ArrowUpRight size={18}/></a>}</div></article>)}
   </section>
   <section className="principles section reveal"><p className="eyebrow">02 / ENGINEERING MINDSET</p><div className="principle-intro"><h2>用模型拓展可能，<br/><span>用工程让它成立。</span></h2><p>业务规则、模型判断、人的复核。<br/>我关心它们如何在同一个系统里配合。</p></div><div className="principle-grid">{[{n:"01",title:"从问题出发",text:"先理解谁在使用、哪一步重复、什么结果有用，再选择模型与技术。",icon:Layers},{n:"02",title:"让边界清楚",text:"区分确定性规则和模型判断，让输入、输出与执行都有可检查的约束。",icon:ShieldCheck},{n:"03",title:"把验证留下",text:"通过测试、运行记录与实验对照，让改进有依据，让问题能够回溯。",icon:Workflow}].map(p=><div key={p.n}><div className="principle-meta"><span>{p.n}</span><p.icon size={24}/></div><h3>{p.title}</h3><p>{p.text}</p></div>)}</div></section>
   <section id="library" className="section library-section"><div className="section-heading"><div><p className="eyebrow">03 / PROJECT INDEX</p><h2>持续构建，持续探索。</h2></div><span className="index-count">{String(projects.length).padStart(2,"0")} PROJECTS & STUDIES</span></div><fieldset className="filter-row" aria-label="筛选项目分类">{categories.map(c=><button key={c} aria-pressed={filter===c} className={filter===c?"active":""} onClick={()=>setFilter(c)}>{c}<span>{c==="全部"?projects.length:projects.filter(p=>p.category===c).length}</span></button>)}</fieldset><p className="sr-only" aria-live="polite">显示 {filtered.length} 个项目</p><div className="project-list">{filtered.map(p=><button className="project-row" key={p.id} onClick={()=>open(p)}><span className="row-index">{String(projects.indexOf(p)+1).padStart(2,"0")}</span><span className="row-main"><strong>{p.title}</strong><span>{p.summary}</span></span><span className="row-category">{p.category}</span><span className="row-status">{p.status}</span><ArrowUpRight size={20}/></button>)}</div></section>
   <section id="about" className="section about-section reveal"><div className="about-heading"><p className="eyebrow">04 / A LITTLE ABOUT ME</p><h2>你好，我是小杨<span>。</span></h2><div className="about-monogram" aria-hidden="true">Y<span>↗</span></div></div><div className="about-copy"><p className="about-lead">我喜欢把业务里那些<br/>“一直靠人工做”的环节，<br/>变成更顺畅的系统。</p><p>我的项目来自跨境电商的具体场景：融资咨询、财务处理、内容运营与海外仓作业。它们让我同时关注产品是否易用、模型是否可控，以及系统能否真正交付。</p><p>目前聚焦 AI 应用开发，也通过机器学习实验持续拓展数据与模型能力。</p><a className="case-link" href="./profile/">山海、运动与音乐：认识代码之外的我 <ArrowUpRight size={18}/></a><div className="about-stack"><span>Python / TypeScript</span><span>React / FastAPI / Node.js</span><span>LLM / 自动化 / 数据工程</span></div><a className="text-link" href="https://github.com/s1166921-png" target="_blank" rel="noreferrer">查看代码与研究 <ArrowUpRight size={17}/></a></div></section>
   <section id="contact" className="contact-section reveal"><div className="eyebrow"><i/> LET’S BUILD SOMETHING USEFUL</div><h2>下一个有价值的项目，<br/>也许从一次交流开始。</h2><div className="contact-actions"><a className="button" href="mailto:249562189@qq.com">联系我 <ArrowUpRight size={19}/></a><button className="copy-email" onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>}<span aria-live="polite">{copied?"邮箱已复制":"249562189@qq.com"}</span></button></div><p>AI 应用开发 · 业务自动化 · 产品工程</p></section>
  </main><footer className="footer"><a className="brand" href="#main" aria-label="回到顶部">Y<span>·</span></a><span>© 2026 小杨 · 保持好奇，继续构建。</span><a href="https://github.com/s1166921-png/ai-project-studio" target="_blank" rel="noreferrer">本站源码 <ArrowUpRight size={14}/></a><a href="#main">BACK TO TOP ↑</a></footer>
  <Dialog open={!!active} onOpenChange={v=>{if(!v)close()}}><DialogContent className="case-dialog">{active&&<><div className="dialog-kicker">{active.category} <span>{active.status}</span></div><DialogTitle className="dialog-title">{active.title}</DialogTitle><DialogDescription className="dialog-description">{active.summary}</DialogDescription><a className="case-link" href={"./projects/"+active.id+"/"}>打开完整项目页面 <ArrowUpRight size={18}/></a><div className="tags">{active.stack.map(s=><span key={s}>{s}</span>)}</div>{active.flow&&<div className="case-flow">{active.flow.map((s,i)=><div key={s}><small>0{i+1}</small><span>{s}</span>{i<active.flow!.length-1&&<ArrowRight size={16}/>}</div>)}</div>}<div className="case-block"><span>THE CHALLENGE</span><h3>要解决的问题</h3><p>{active.problem}</p></div><div className="case-block"><span>THE APPROACH</span><h3>系统如何工作</h3><p>{active.solution}</p></div><div className="case-block"><span>KEY DECISIONS</span><h3>关键工程选择</h3><ul>{active.decisions.map(d=><li key={d}>{d}</li>)}</ul></div>{active.evidence.length>0&&<div className="evidence-links">{active.evidence.map(([label,url])=><a key={url} href={url} target="_blank" rel="noreferrer">{label}<ArrowUpRight size={17}/></a>)}</div>}<p className="case-boundary">{active.boundary}</p><a className="case-contact" href="mailto:249562189@qq.com"><Mail size={16}/> 交流这个项目 <ArrowUpRight size={16}/></a></>}</DialogContent></Dialog>
 </div>
}





