"use client";
import { useState } from 'react';
import { ArrowUpRight, ArrowDown, ArrowLeft, Pause, Play, Mountain, Waves, Trophy, Music2, Activity, TrendingUp, Plus } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import TechField from '../tech-field';
import './profile.css';
const photos={portrait:{file:'mountain-portrait.jpg',label:'山野中的我',description:'徒步途中，与雪山同框。'},summit:{file:'summit-5018.jpg',label:'走到 5018 米',description:'登顶留影，身旁的海拔标识为 5018 米。'},night:{file:'night-summit.jpg',label:'雪山与星空',description:'把山野的夜色，留进生活的相册。'},singer:{file:'singer-award.jpg',label:'菁英歌手',description:'「这就是歌手」赛事荣誉。'},star:{file:'rising-star.jpg',label:'明日之星',description:'「这就是歌手」赛事荣誉。'},league:{file:'league-record.jpg',label:'英雄联盟战绩记录',description:'个人竞技经历的记录。'},perfume:{file:'perfume-workshop.jpg',label:'另一种创作：调香体验',description:'一次初级调香体验，也是一种探索表达的方式。'}};
type Photo=typeof photos[keyof typeof photos];
export default function Profile(){const [paused,setPaused]=useState(false),[active,setActive]=useState<Photo|null>(null);const photo=(p:Photo,className:string)=> <button className={'life-photo '+className} onClick={()=>setActive(p)} aria-label={'放大查看：'+p.label}><img src={'../profile/'+p.file} alt={p.label} loading="lazy"/><span className="photo-open"><Plus size={16}/> 查看照片</span></button>;
return <div className={'life-page'+(paused?' motion-paused':'')}><a className="skip-link" href="#life-main">跳至主要内容</a><header className="life-nav"><a href="../" className="life-logo">YANG<span>PERSONAL FIELD NOTES</span></a><nav aria-label="个人名片导航"><a href="../#tools">开发作品 <ArrowUpRight size={14}/></a><a href="#life-contact">联系我</a><button onClick={()=>setPaused(!paused)} aria-label={paused?'播放页面动画':'暂停页面动画'} aria-pressed={paused}>{paused?<Play size={16}/>:<Pause size={16}/>}</button></nav></header><main id="life-main"><section className="life-hero"><TechField paused={paused}/><div className="life-intro"><p className="life-kicker"><span/> HELLO, I'M YANG</p><h1>认真构建。<br/><em>尽兴生活。</em></h1><p className="life-lead">我是小杨，一名 AI 应用开发者。<br/>在代码里解决问题，也在山海之间、<br/>球场之上与音乐里，探索自己的可能。</p><a href="../#work" className="life-cta">看我的开发作品 <ArrowUpRight size={18}/></a><div className="life-coordinates"><span>BUILD WITH CURIOSITY</span><span>LIVE WITH RANGE ↗</span></div></div><div className="life-portrait"><img src="../profile/mountain-portrait.jpg" alt="小杨背着背包站在雪山前" fetchPriority="high"/><div className="portrait-stamp">Y.<small>OUTSIDE THE SCREEN</small></div><span className="portrait-caption">山海之间，代码之外。</span><span className="portrait-cross">+</span></div><a className="life-scroll" href="#explore">SCROLL TO DISCOVER <ArrowDown size={15}/></a></section><div className="life-index"><a href="#explore"><Mountain/>山海探索</a><a href="#compete"><Trophy/>竞技与运动</a><a href="#music"><Music2/>音乐与表达</a><a href="#invest"><TrendingUp/>投资与研究</a></div>
<section id="explore" className="life-section expedition"><div className="life-section-heading"><p className="life-kicker">01 / BEYOND THE HORIZON</p><h2>向山而行。<br/><span>向海而潜。</span></h2><p>喜欢爬山、徒步，也喜欢水下的另一种安静。<br/>有些风景，需要自己走进去。</p></div><div className="expedition-grid"><div className="summit-card">{photo(photos.summit,'summit-photo')}<div className="summit-caption"><span>登顶记录</span><strong>5,018<small>M</small></strong><p>一步一步，走到山顶。</p></div></div><div className="night-card">{photo(photos.night,'night-photo')}<div className="night-caption"><span>AFTER DARK</span><p>山野有自己的光。</p></div></div><div className="dive-card"><div className="dive-orbits" aria-hidden="true"><i/><i/><i/></div><Waves size={30}/><p className="life-kicker">BENEATH THE SURFACE</p><h3>水下的探索资格。</h3><div className="dive-qualifications"><div><strong>OW</strong><span>开放水域潜水员</span></div><div><strong>AOW</strong><span>进阶开放水域潜水员</span></div></div><p>NAUI 双证持有者。<br/>从山野到水下，继续拓展生活的半径。</p></div></div></section>
<section id="compete" className="life-section compete"><div className="life-section-heading"><p className="life-kicker">02 / PLAY WITH INTENT</p><h2>热爱上场。<br/><span>也享受进步的过程。</span></h2><p>球场、训练与竞技，是我生活的另一部分。</p></div><div className="competition-grid"><div className="sports-panel"><div className="sport-emblem" aria-hidden="true"><Activity size={58}/></div><p className="life-kicker">KEEP SHOWING UP</p><div className="sport-numbers"><div><strong>冠军</strong><span>篮球比赛经历</span></div><div><strong>2+<small>年</small></strong><span>持续健身</span></div></div><p>喜欢跑步、游泳，也享受羽毛球和乒乓球的对抗与节奏。</p><div className="sports-tags">{['篮球','健身','跑步','游泳','羽毛球','乒乓球'].map(s=><span key={s}>{s}</span>)}</div></div><div className="rank-panel"><p className="life-kicker">COMPETITIVE RECORD</p><div className="rank-row"><span>LEAGUE OF LEGENDS<small>一区 · 单排</small></span><strong>大师 <em>441</em><small>点</small></strong></div><div className="rank-row"><span>VALORANT<small>瓦洛兰特</small></span><strong>超凡</strong></div><div className="rank-row"><span>LAN COMPETITION<small>线下竞技</small></span><strong className="rank-small">CSGO / LOL<small>网吧赛经历</small></strong></div><button className="record-link" onClick={()=>setActive(photos.league)}>查看战绩照片 <ArrowUpRight size={16}/></button><p className="record-note">段位与比赛经历为个人记录，不代表当前赛季实时状态。</p></div></div></section>
<section id="music" className="life-section music"><div className="music-story"><p className="life-kicker">03 / FIND MY VOICE</p><h2>代码之外，<br/><span>还有我的声音。</span></h2><div className="sound-wave" aria-hidden="true">{[22,44,31,62,80,45,95,59,37,75,54,30,65,84,42,24].map((h,i)=><i key={i} style={{height:h+'%',animationDelay:(-i*.17)+'s'}}/>)}</div><p>喜欢唱歌，也喜欢站上舞台。<br/>让热爱从日常练习，走到被听见的时刻。</p><div className="music-awards"><span>校园十佳歌手</span><span>「这就是歌手」菁英歌手</span><span>「这就是歌手」明日之星</span></div></div><div className="award-photos"><figure>{photo(photos.singer,'award-photo')}<figcaption>菁英歌手 / 荣誉记录</figcaption></figure><figure>{photo(photos.star,'award-photo')}<figcaption>明日之星 / 荣誉记录</figcaption></figure></div></section>
<section id="invest" className="life-section investing"><div><p className="life-kicker">04 / A LONGER PERSPECTIVE</p><h2>从 2020 年，<br/><span>开始自己的市场观察。</span></h2><p>投资是持续多年的个人实践。<br/>从关注市场，到数据分析与量化研究，<br/>也把这份兴趣延伸进了自己的开发项目。</p><a className="life-text-link" href="../projects/ml/">查看机器学习与量化研究 <ArrowUpRight size={17}/></a></div><div className="investment-note"><span>SINCE</span><strong>2020</strong><div className="investment-line"/><p>持续研究 · 实盘经验 · 长期参与</p><small>个人自述：自 2020 年开始投资，并持续盈利。收益口径与具体记录可在交流中进一步说明。</small></div></section>
<section className="life-aside">{photo(photos.perfume,'perfume-photo')}<div><p className="life-kicker">AND A LITTLE MORE CURIOSITY</p><h2>不止一种兴趣，<br/>不止一种表达。</h2><p>一次调香体验，也是对气味、组合与创作的探索。<br/>保留好奇心，让生活不断出现新的可能。</p></div></section>
<section id="life-contact" className="life-contact"><p className="life-kicker">LET'S CONNECT</p><h2>可以聊 AI，<br/>也可以聊下一座山。</h2><a href="mailto:249562189@qq.com" className="life-cta">249562189@qq.com <ArrowUpRight size={19}/></a><a href="../" className="life-back"><ArrowLeft size={16}/> 回到开发作品集</a></section></main><footer className="life-footer"><span>YANG / BUILD. EXPLORE. EXPRESS.</span><a href="#life-main">回到顶部 ↑</a></footer><Dialog open={!!active} onOpenChange={v=>{if(!v)setActive(null)}}><DialogContent className="life-lightbox">{active&&<><DialogTitle>{active.label}</DialogTitle><img src={'../profile/'+active.file} alt={active.label}/><DialogDescription>{active.description}</DialogDescription></>}</DialogContent></Dialog></div>
}
