import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowUpRight, ArrowRight, Check, Code2 } from 'lucide-react';
import { projects } from '../../projects';
export function generateStaticParams(){return projects.map(p=>({id:p.id}))}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const p=projects.find(x=>x.id===id);return {title:p?`${p.title} — YANG 项目案例`:'项目案例',description:p?.summary}}
export default async function ProjectPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const p=projects.find(x=>x.id===id);if(!p)notFound();
 const next=projects[(projects.indexOf(p)+1)%projects.length];
 return <div className="portfolio detail-page"><header className="detail-header"><a href="../../#tools"><ArrowLeft size={17}/> 返回作品集</a><a href="../../" className="detail-brand">YANG <span>/ PROJECT FILE</span></a></header><main className="detail-shell"><section className="detail-hero"><p className="eyebrow">CASE STUDY / {p.id.toUpperCase()}</p><div className="detail-meta"><span>{p.category}</span><span>{p.status}</span></div><h1>{p.title}</h1><p className="detail-tagline">{p.tagline||p.summary}</p><div className="tags">{p.stack.map(t=><span key={t}>{t}</span>)}</div></section><div className="detail-columns"><article className="detail-content"><section><p className="eyebrow">01 / CONTEXT</p><h2>从一个具体问题开始。</h2><p>{p.problem}</p>{p.audience&&<p className="detail-audience">使用者 / {p.audience}</p>}</section><section><p className="eyebrow">02 / IMPLEMENTATION</p><h2>把业务步骤，连成系统。</h2><p>{p.solution}</p><div className="detail-flow">{(p.flow||['业务输入','处理与校验','结果交付']).map((s,i)=><div key={s}><small>STEP 0{i+1}</small><strong>{s}</strong><ArrowRight size={17}/></div>)}</div></section><section><p className="eyebrow">03 / ENGINEERING VALUE</p><h2>值得展开的工程选择。</h2><div className="decision-list">{p.decisions.map((d,i)=><div key={d}><span>0{i+1}</span><p>{d}</p></div>)}</div></section>{p.experience&&<section><p className="eyebrow">04 / WALKTHROUGH</p><h2>打开后，可以重点看什么。</h2><ul className="experience-list">{p.experience.map(d=><li key={d}><Check size={18}/>{d}</li>)}</ul></section>}<section className="detail-boundary"><h3>项目状态与范围</h3><p>{p.boundary}</p></section></article><aside className="project-access"><div className="access-panel"><div className="access-heading"><span className="signal-dot"/> PROJECT ACCESS</div><h2>进入项目</h2><p>网页体验、代码实现与案例说明。</p>{p.links?.map(link=><a className="access-link" key={link.url} href={link.url} target="_blank" rel="noopener noreferrer"><small>{link.kind}</small><strong>{link.label}<ArrowUpRight size={18}/></strong><span>{link.note}</span></a>)}{p.accessNote&&<p className="access-note">{p.accessNote}</p>}{p.evidence.map(([label,url])=><a className="source-link" href={url} key={url} target="_blank" rel="noopener noreferrer"><Code2 size={16}/>{label}<ArrowUpRight size={15}/></a>)}{!p.links?.length&&!p.evidence.length&&<p className="access-note">可在交流时演示项目流程；公司源码未公开。</p>}<a className="access-contact" href={`mailto:249562189@qq.com?subject=${encodeURIComponent('交流项目：'+p.title)}`}>交流项目 / 预约演示 <ArrowUpRight size={16}/></a></div></aside></div><a className="next-case" href={`../${next.id}/`}><span>继续了解下一个项目</span><strong>{next.title}</strong><ArrowUpRight size={26}/></a></main><footer className="detail-footer">YANG / AI APPLICATION ENGINEERING <a href="../../#tools">全部工具与项目 ↑</a></footer></div>
}
